[package]
name = "propel-oauth"
version = "0.1.0"
authors = [".."]
edition = "2021"

[dependencies]
dotenv = "0.15.0"
envy = "0.4.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
mockito = "0.28"


